#pragma config(Motor,  motorA,          arm_motor,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int target = -40; // encoder ticks 

float kf = 1.5;
float kp = 5;
float kd = 10;

int feedForeward(int input){
	int output = input*kf;
	return output;
}

int integral(int input){
	int output = input - target;
	return output;
}	

int control(int input){
	int output = (int)(kp*(float)input+kd);
	return output;
}
int plant(int input){
	motor[arm_motor] = input;
	return nMotorEncoder[arm_motor];
}

task steady(){
	int output = 0;
	nMotorEncoder[arm_motor] = 0;
	while(true){
		int c = control(target-output);
		int f = feedForeward(target);
		int in = integral(output);
		nxtDisplayString(1,"%d", nMotorEncoder[arm_motor]);
		nxtDisplayString(2,"%d", f);
		nxtDisplayString(3,"%d", in);
		output = plant(c+f);
		if(nNxtButtonPressed == kExitButton){
			motor[arm_motor] = 0;
		}
			
	}
}

task main()
{
	
	while(true){
		startTask(steady);
		while(nNxtButtonPressed != kExitButton) {}
	}	
}
